export {default as problem1 }from './problem1.js';
export {default as problem2 }from './problem2.js';
export {default as problem3 }from './problem3.js';
export {default as problem4 }from './problem4.js';
// export {default as problem5 }from './problem5.js';
// export {default as problem6 }from './problem6.js';
// export {default as problem7 }from './problem7.js';
// export {default as problem8 }from './problem8.js';
// export {default as problem9 }from './problem9.js';
// export {default as problem10 }from './problem10.js';